# Generated by Django 5.0 on 2024-01-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_section_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
