# Generated by Django 5.0 on 2024-01-16 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_onlineuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OnlineUser',
        ),
    ]
