# Generated by Django 5.0 on 2024-01-17 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_alter_vote_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='rank',
            new_name='votes',
        ),
    ]
