# Generated by Django 5.0 on 2024-01-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_logged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_logged',
            field=models.BooleanField(default=True),
        ),
    ]
